name: 21f3001224@ds.study.iitm.ac.in

on:
  schedule:
    - cron: "30 7 * * *"
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auto commit daily update
        run: |
          git config --local user.email "21f3001224@ds.study.iitm.ac.in"
          git config --local user.name "GitHub Actions Bot"
          echo "Updated on $(date)" >> daily.txt
          git add daily.txt
          git commit -m "Daily update [skip ci]" || echo "No changes to commit"
          git push
